### ISSUE TITLE
Quality of Download

### ISSUE THREAD

**Issue by ghost** [eviabs/downtify-premium#34]

**Comment by lovemonkeyz** [comment]
As this is intended for Spotify Premium users, it has a set bitrate of 320 kbps (Spotify maximum bitrate with premium). 

I'm not sure if this can be changed to lower values, I'd have to dig through the code some more for that. @eviabs - Since you're the main dev, is it one of the libraries used that determines setting bitrate, or is it set in the source code and can therefor be added as an option in the config file? 

On another note, would changing bitrate even have an affect on download speeds? Since it records and re-encodes the songs, my guess is that it won't, but I also lack enough knowledge of the underlying tech :D

**Comment by kirill-develops** [comment]
thank you for the response!

it's great to hear that it would be 320 kbps, the only thing better would be lossless but you can't reencode it to a higher quality so 320kbps works for me.

cheers for that one
